### ISSUE TITLE
Unable to compile from source 

### ISSUE THREAD

**Issue by vascomedici** [energywebfoundation/energyweb-client#3] opened 2017-12-13 11:25 UTC
I followed the instructions to install from source and I got the same error when running `cargo build --release` on both amd64 and ARMv7 architecture 

> Updating git repository https://github.com/paritytech/js-precompiled.git
> error: failed to load source for a dependency on parity-ui-precompiled
> 
> Caused by:
>   Unable to update https://github.com/paritytech/js-precompiled.git#1626d642

**Comment by dstreppa** [comment] 2017-12-13 13:56
+1

**Comment by solsista** [comment] 2017-12-15 08:56
Same here on Ubuntu 16.04.3 LTS
I've had Parity installed from Parity.io - not built from source
I cloned and attempted to build energyweb-client according to readme.

Parity
  version Parity/v1.8.0-beta-9882902-20171015/x86_64-linux-gnu/rustc1.20.0

When running build accroding to README I get:
 Updating git repository `https://github.com/paritytech/js-precompiled.git`
error: failed to load source for a dependency on `parity-ui-precompiled`

Caused by:
  Unable to update https://github.com/paritytech/js-precompiled.git#1626d642

Caused by:
  [4/-3] revspec '1626d64235241e75c531eece004a4923d9d4fcc6' not found

Could be a versioning issue across builds:
https://github.com/energywebfoundation/energyweb-client/blob/379b993fee67c2b3ada7665af77b86443f05b8bb/Cargo.lock

Tried htese https://github.com/rust-lang/cargo/issues/1322
cargo clean: nothing
cargo update:
~/.cargo/bin/cargo update --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/paritytech/rust-secp256k1`
    Updating git repository `https://github.com/paritytech/bn`
    Updating git repository `https://github.com/paritytech/hyper`
    Updating git repository `https://github.com/paritytech/rust-rocksdb`
    Updating git repository `https://github.com/paritytech/jsonrpc.git`
    Updating git repository `https://github.com/paritytech/hidapi-rs`
    Updating git repository `https://github.com/paritytech/libusb-rs`
    Updating git repository `https://github.com/paritytech/trezor-sys`
    Updating git repository `https://github.com/paritytech/wasm-utils`
    Updating git repository `https://github.com/paritytech/rust-ctrlc.git`
    Updating git repository `https://github.com/paritytech/js-precompiled.git`
    Updating git repository `https://github.com/paritytech/js-precompiled.git`
error: failed to load source for a dependency on `parity-ui-precompiled`

Caused by:
  Unable to update https://github.com/paritytech/js-precompiled.git

Caused by:
  Could not find Cargo.toml in `/home/<user>/.cargo/git/checkouts/js-precompiled-3cd543bab48e48d9/4fb588a`

Will try deleting lock file, and/or also building my Parity from source (over the weekend ;)
But I have a feeling this is a very small issue, that maintainers could fix easily by looking into Cargo.lock , .toml

**Comment by ConnorBlockchain** [comment] 2017-12-21 14:55
+1

**Comment by jbentke** [comment] 2018-01-04 09:12
We are aware of those issues and are currently waiting on parity to fix it. It has something to do with the user interface which is different from the standard parity. 

You can work around that by either using a pre-compiled version or compiling the parity source code and pass the chain specification as a parameter with `--chain /path/to/chain/spec` which can be found here https://github.com/energywebfoundation/energyweb-client/blob/master/ethcore/res/ethereum/tobalaba.json

**Comment by rickkubin** [comment] 2018-01-10 16:47
I am still experiencing this problem. Any further info on a fix?

**Comment by jacogr** [comment] 2018-01-11 10:51
To build from source, build using -

`cargo build --release --no-default-features --features ui`

Using the default `cargo build --release` will fail on the UI portions. The above mimics the way it actually gets built on CI. In addition to the Rust toolchain, make sure you have Node.js on your machine.

**Comment by jbentke** [comment] 2018-01-11 15:45
```
error: failed to run custom build command for `parity-ui-old-dev v1.9.0 (file:///Users/jbentke/Documents/EWF_Test/energyweb-client/js-old)`
process didn't exit successfully: `/Users/jbentke/Documents/EWF_Test/energyweb-client/target/release/build/parity-ui-old-dev-19c7bfcf77232208/build-script-build` (exit code: 101)
--- stderr
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: sha1-ycYKSKRu5FL7MqccMXuV5aofyz0= integrity checksum failed when using sha1: wanted sha1-ycYKSKRu5FL7MqccMXuV5aofyz0= but got sha1-bvTpVOp9z1T2aq0v56pCGTLZ7Xc=. (41508 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:110:20)
    at Transform.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: sha1-ycYKSKRu5FL7MqccMXuV5aofyz0= integrity checksum failed when using sha1: wanted sha1-ycYKSKRu5FL7MqccMXuV5aofyz0= but got sha1-bvTpVOp9z1T2aq0v56pCGTLZ7Xc=. (41508 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:110:20)
    at Transform.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! cancel after 1 retries!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jbentke/.npm/_logs/2018-01-11T15_16_44_259Z-debug.log
thread 'main' panicked at 'There was an error installing dependencies.', /Users/jbentke/Documents/EWF_Test/energyweb-client/target/release/build/parity-dapps-glue-f8a6c29c7e8ff932/out/lib.rs:476
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

@jacogr

**Comment by rickkubin** [comment] 2018-01-11 21:14
Hi there-

I tried again and got the same result: I do have rust and node.js installed. I was able to install and run Parity itself.

Any ideas?

RICKs-MacBook-Pro:energyweb-client rickkubin$ cargo build --release --no-default-features --features ui --verbose
    Updating git repository `https://github.com/paritytech/js-precompiled.git`
error: failed to load source for a dependency on `parity-ui-precompiled`        

Caused by:
  Unable to update https://github.com/paritytech/js-precompiled.git#1626d642

Caused by:
  [4/-3] revspec '1626d64235241e75c531eece004a4923d9d4fcc6' not found

**Comment by maciejhirsz** [comment] 2018-01-12 11:25
Opened a PR that should remedy the issues. Is there a gitlab repo the PR should be replicated to?

**Comment by Simonjohanning** [comment] 2018-01-31 18:30
I have a similar problem, but with the hidapi dependency.
I get the following error message: 


error: failed to load source for a dependency on `hidapi`

Caused by:
  Unable to update https://github.com/paritytech/hidapi-rs#2e618213

Caused by:
  failed to update submodule `etc/hidapi`

Caused by:
  [23/-1] authentication required but no callback set

The first 8 work fine:
$ cargo build --release --no-default-features --features ui
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/paritytech/rust-secp256k1`
    Updating git repository `https://github.com/paritytech/bn`
    Updating git repository `https://github.com/paritytech/hyper`
    Updating git repository `https://github.com/paritytech/rust-rocksdb`
    Updating git repository `https://github.com/paritytech/libusb-rs`
    Updating git repository `https://github.com/paritytech/trezor-sys`
    Updating git repository `https://github.com/paritytech/hidapi-rs`
error: failed to load source for a dependency on `hidapi`

Caused by:
  Unable to update https://github.com/paritytech/hidapi-rs#2e618213

Caused by:
  failed to update submodule `etc/hidapi`

To learn more, run the command again with --verbose.

I'm using ubuntu 16.04 LTS (64-bit) on a HP-Compaq-Pro-6300-MT with an Intel® Core™ i5-3570 CPU @ 3.40GHz × 4

**Comment by maciejhirsz** [comment] 2018-02-01 17:42
@Simonjohanning I've tried clearing all the cargo cache and what not to reproduce this on an intel CPU ubuntu 16.10 and it always compiles for me.

Did you try updating rustc and cargo to latest stable? I'd also check if you are on latest `master`, and whether or not `cargo update` fixes it for you (although it will make changes to `Cargo.lock` file, which result in some issues with a dependency had a breaking change in a patch update for whatever reason).

Also since my PR is now merged, you can just run `cargo build --release` to make a build without having to bother with feature flags (adding them makes no difference).

**Comment by Simonjohanning** [comment] 2018-02-01 17:58
Dear Maciej,
Thank you very much for your email. I tried out what you suggested.
Unfortunately I found a multiple link to the ring-asm library (from whisper
and parity v1.9.0; see output below) after updating cargo (which seems to
have worked fine). I also seem to have the current version of rust:
$ rustc --version
rustc 1.23.0 (766bd11c8 2018-01-01)
Thanks a lot for your time!
Simon

$ cargo build --release
 Downloading fdlimit v0.1.1
 Downloading futures
v0.1.18
 Downloading ansi_term
v0.9.0
 Downloading log
v0.3.9
 Downloading semver
v0.6.0
 Downloading serde
v1.0.27
 Downloading num_cpus
v1.8.0
 Downloading serde_json
v1.0.9
 Downloading isatty
v0.1.6
 Downloading env_logger
v0.4.3
 Downloading docopt
v0.8.3
 Downloading futures-cpupool
v0.1.8
 Downloading ws2_32-sys
v0.2.1
 Downloading toml
v0.4.5
 Downloading time
v0.1.39
 Downloading clap
v2.29.2
 Downloading app_dirs
v1.1.1
 Downloading regex
v0.2.5
 Downloading number_prefix
v0.2.7
 Downloading rustc-hex
v1.0.0
 Downloading parking_lot
v0.4.8
 Downloading serde_derive
v1.0.27
 Downloading rpassword
v1.0.2
 Downloading libc
v0.2.36
 Downloading heapsize
v0.4.2
 Downloading elastic-array
v0.9.0
 Downloading tiny-keccak
v1.4.0
 Downloading target_info
v0.1.0
 Downloading bigint
v4.2.0
 Downloading rand
v0.3.20
 Downloading crunchy
v0.1.6
 Downloading byteorder
v1.2.1
 Downloading rustc_version
v0.2.1
 Downloading semver-parser
v0.7.0
 Downloading owning_ref
v0.3.3
 Downloading parking_lot_core
v0.2.10
 Downloading stable_deref_trait
v1.0.0
 Downloading smallvec
v0.6.0
 Downloading cc
v1.0.4
 Downloading rayon
v0.9.0
 Downloading rayon-core
v1.3.0
 Downloading either
v1.4.0
 Downloading lazy_static
v0.2.11
 Downloading coco
v0.1.1
 Downloading scopeguard
v0.3.3
 Downloading log
v0.4.1
 Downloading cfg-if
v0.1.2
 Downloading arrayvec
v0.3.25
 Downloading memchr
v2.0.1
 Downloading thread_local
v0.3.5
 Downloading regex-syntax
v0.4.2
 Downloading utf8-ranges
v1.0.0
 Downloading aho-corasick
v0.6.4
 Downloading lazy_static
v1.0.0
 Downloading unreachable
v1.0.0
 Downloading void
v1.0.2
 Downloading odds
v0.2.26
 Downloading nodrop
v0.1.12
 Downloading error-chain
v0.11.0
 Downloading backtrace
v0.3.5
 Downloading rustc-demangle
v0.1.5
 Downloading local-encoding
v0.2.0
 Downloading skeptic
v0.4.0
 Downloading pulldown-cmark
v0.0.3
 Downloading tempdir
v0.3.6
 Downloading getopts
v0.2.17
 Downloading rand
v0.4.2
 Downloading remove_dir_all
v0.3.0
 Downloading winapi
v0.2.8
 Downloading kernel32-sys
v0.2.2
 Downloading winapi-build
v0.1.1
 Downloading gcc
v0.3.54
 Downloading rayon
v0.8.2
 Downloading arrayvec
v0.4.7
 Downloading rustc-serialize
v0.3.24
 Downloading vergen
v0.1.1
 Downloading rustc_version
v0.1.7
 Downloading bitflags
v0.7.0
 Downloading semver
v0.1.20
 Downloading slab
v0.2.0
 Downloading bytes
v0.4.6
 Downloading ipnetwork
v0.12.7
 Downloading igd
v0.6.0
 Downloading mio
v0.6.12
 Downloading rust-crypto
v0.2.36
 Downloading dtoa
v0.4.2
 Downloading num-traits
v0.1.42
 Downloading itoa
v0.3.4
 Downloading crossbeam
v0.2.12
 Downloading iovec
v0.1.2
 Downloading net2
v0.2.31
 Downloading lazycell
v0.6.0
 Downloading slab
v0.3.0
 Downloading subtle
v0.1.0
 Downloading hyper
v0.10.13
 Downloading xml-rs
v0.3.6
 Downloading xmltree
v0.3.2
 Downloading traitobject
v0.1.0
 Downloading typeable
v0.1.2
 Downloading httparse
v1.2.4
 Downloading language-tags
v0.2.2
 Downloading mime
v0.2.6
 Downloading base64
v0.6.0
 Downloading url
v1.6.0
 Downloading unicase
v1.4.2
 Downloading safemem
v0.2.0
 Downloading percent-encoding
v1.0.1
 Downloading matches
v0.1.6
 Downloading idna
v0.1.4
 Downloading unicode-normalization
v0.1.5
 Downloading unicode-bidi
v0.3.4
 Downloading version_check
v0.1.3
 Downloading smallvec
v0.4.4
 Downloading itertools
v0.5.10
 Downloading bincode
v0.8.0
 Downloading syn
v0.11.11
 Downloading quote
v0.3.15
 Downloading unicode-xid
v0.0.4
 Downloading synom
v0.11.3
 Downloading bit-set
v0.4.0
 Downloading lru-cache
v0.1.1
 Downloading linked-hash-map
v0.4.2
 Downloading serde_derive_internals
v0.19.0
 Downloading bit-vec
v0.4.4
 Downloading num
v0.1.41
 Downloading transient-hashmap
v0.4.0
 Downloading linked-hash-map
v0.5.1
 Downloading bloomchain
v0.1.0
 Downloading primal
v0.2.3
 Downloading memmap
v0.5.2
 Downloading primal-sieve
v0.2.8
 Downloading primal-estimate
v0.2.1
 Downloading primal-check
v0.2.3
 Downloading primal-bit
v0.2.4
 Downloading hamming
v0.1.3
 Downloading num-integer
v0.1.35
 Downloading reqwest
v0.7.3
 Downloading hyper
v0.11.16
 Downloading tokio-core
v0.1.12
 Downloading hyper-tls
v0.1.2
 Downloading tokio-tls
v0.1.4
 Downloading tokio-io
v0.1.4
 Downloading serde_urlencoded
v0.5.1
 Downloading libflate
v0.1.14
 Downloading native-tls
v0.1.5
 Downloading mime
v0.3.5
 Downloading relay
v0.1.1
 Downloading base64
v0.9.0
 Downloading tokio-service
v0.1.0
 Downloading tokio-proto
v0.1.1
 Downloading unicase
v2.1.0
 Downloading scoped-tls
v0.1.0
 Downloading slab
v0.4.0
 Downloading take
v0.1.0
 Downloading smallvec
v0.2.1
 Downloading crc
v1.7.0
 Downloading adler32
v1.0.2
 Downloading build_const
v0.2.0
 Downloading num-rational
v0.1.41
 Downloading num-bigint
v0.1.41
 Downloading num-iter
v0.1.34
 Downloading num-complex
v0.1.41
 Downloading ethabi
v4.2.0
 Downloading heck
v0.2.1
 Downloading unicode-segmentation
v1.2.0
 Downloading parity-wasm
v0.14.6
 Downloading parity-wasm
v0.23.0
 Downloading glob
v0.2.11
 Downloading bitflags
v1.0.1
 Downloading strsim
v0.6.0
 Downloading unicode-width
v0.1.4
 Downloading ansi_term
v0.10.2
 Downloading textwrap
v0.9.0
 Downloading vec_map
v0.8.0
 Downloading atty
v0.2.6
 Downloading parking_lot
v0.5.3
 Downloading protobuf
v1.4.3
 Downloading siphasher
v0.1.3
 Downloading parity-wordlist
v1.2.0
 Downloading spmc
v0.2.2
 Downloading cookie
v0.3.1
 Downloading vecio
v0.1.0
 Downloading quick-error
v1.2.1
 Downloading globset
v0.1.4
 Downloading fnv
v1.0.6
 Downloading memchr
v1.0.2
 Downloading mime_guess
v2.0.0-alpha.3
 Downloading phf
v0.7.21
 Downloading phf_shared
v0.7.21
 Downloading siphasher
v0.2.2
 Downloading phf_codegen
v0.7.21
 Downloading phf_generator
v0.7.21
 Downloading ntp
v0.3.1
 Downloading custom_derive
v0.1.7
 Downloading conv
v0.3.3
 Downloading sha1
v0.2.0
 Downloading pretty_assertions
v0.1.2
 Downloading tokio-timer
v0.1.2
 Downloading multihash
v0.6.0
 Downloading order-stat
v0.1.3
 Downloading cid
v0.2.3
 Downloading difference
v1.0.0
 Downloading ring
v0.9.7
 Downloading untrusted
v0.5.1
 Downloading rayon
v0.7.1
 Downloading tokio-uds
v0.1.7
 Downloading miow
v0.2.1
 Downloading mio-uds
v0.6.4
 Downloading multihash
v0.7.0
 Downloading integer-encoding
v1.0.5
 Downloading multibase
v0.6.0
 Downloading ring
v0.12.1
 Downloading base-x
v0.2.2
 Downloading rprompt
v1.0.3
 Downloading hex
v0.2.0
 Downloading bitflags
v0.9.1
 Downloading ordered-float
v0.5.0
 Downloading unreachable
v0.1.1
 Downloading base32
v0.3.1
 Downloading zip
v0.1.19
 Downloading parity-dapps-glue
v1.9.1
 Downloading flate2
v0.2.20
 Downloading msdos_time
v0.1.5
 Downloading podio
v0.1.6
 Downloading miniz-sys
v0.1.10
 Downloading syntex_syntax
v0.58.1
 Downloading quasi
v0.32.0
 Downloading aster
v0.41.0
 Downloading syntex
v0.58.1
 Downloading syntex_pos
v0.58.1
 Downloading bitflags
v0.8.2
 Downloading syntex_errors
v0.58.1
 Downloading term
v0.4.6
 Downloading quasi_codegen
v0.32.0
 Downloading daemonize
v0.2.3
 Downloading backtrace-sys
v0.1.16
 Downloading openssl
v0.9.23
 Downloading foreign-types
v0.3.2
 Downloading openssl-sys
v0.9.24
 Downloading foreign-types-shared
v0.1.1
 Downloading pkg-config
v0.3.9
 Downloading xdg
v2.1.0
error: Multiple packages link to native library `ring-asm`. A native
library can be linked only once.

Package `ring v0.9.7`
    ... which is depended on by `parity-whisper v0.1.0
(file:///home/simon/projects/energyweb-client/whisper)`
    ... which is depended on by `parity v1.9.0
(file:///home/simon/projects/energyweb-client)`
links to native library `ring-asm`.

Package `ring v0.12.1`
    ... which is depended on by `multihash v0.7.0`
    ... which is depended on by `cid v0.2.3`
    ... which is depended on by `parity-ipfs-api v1.9.0
(file:///home/simon/projects/energyweb-client/ipfs)`
    ... which is depended on by `parity v1.9.0
(file:///home/simon/projects/energyweb-client)`
also links to native library `ring-asm`.

**Comment by maciejhirsz** [comment] 2018-02-13 17:19
@Simonjohanning sorry for only replying now. I was able to reproduce that issue, please checkout `Cargo.lock` to the version that is in the repo right now, remove the `target` folder with all of it's contents and try `cargo build --release`.

**Comment by jbentke** [comment] 2018-03-12 15:45
I just tried the new version. Should work normal with cargo build --release again.

**Closed by jbentke** 2018-03-12 15:45 UTC
